//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quick.Onvif.AuthenticationBehavior
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", ConfigurationName="Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort")]
    public interface AuthenticationBehaviorPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetServiceCapabilities", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Capabilities")]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.ServiceCapabilities> GetServiceCapabilitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileIn" +
            "fo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoResponse> GetAuthenticationProfileInfoAsync(Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoRequest request);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileIn" +
            "foList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoListResponse> GetAuthenticationProfileInfoListAsync(Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfilesResponse> GetAuthenticationProfilesAsync(Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfilesRequest request);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetAuthenticationProfileLi" +
            "st", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileListResponse> GetAuthenticationProfileListAsync(Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/CreateAuthenticationProfil" +
            "e", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Token")]
        System.Threading.Tasks.Task<string> CreateAuthenticationProfileAsync(Quick.Onvif.AuthenticationBehavior.AuthenticationProfile AuthenticationProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/SetAuthenticationProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task SetAuthenticationProfileAsync(Quick.Onvif.AuthenticationBehavior.AuthenticationProfile AuthenticationProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/ModifyAuthenticationProfil" +
            "e", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task ModifyAuthenticationProfileAsync(Quick.Onvif.AuthenticationBehavior.AuthenticationProfile AuthenticationProfile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/DeleteAuthenticationProfil" +
            "e", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task DeleteAuthenticationProfileAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoResponse> GetSecurityLevelInfoAsync(Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoRequest request);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelInfoList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoListResponse> GetSecurityLevelInfoListAsync(Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelsResponse> GetSecurityLevelsAsync(Quick.Onvif.AuthenticationBehavior.GetSecurityLevelsRequest request);
        
        // CODEGEN: 正在生成消息协定，因为操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/GetSecurityLevelList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelListResponse> GetSecurityLevelListAsync(Quick.Onvif.AuthenticationBehavior.GetSecurityLevelListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/CreateSecurityLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Token")]
        System.Threading.Tasks.Task<string> CreateSecurityLevelAsync(Quick.Onvif.AuthenticationBehavior.SecurityLevel SecurityLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/SetSecurityLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task SetSecurityLevelAsync(Quick.Onvif.AuthenticationBehavior.SecurityLevel SecurityLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/ModifySecurityLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task ModifySecurityLevelAsync(Quick.Onvif.AuthenticationBehavior.SecurityLevel SecurityLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.onvif.org/ver10/authenticationbehavior/wsdl/DeleteSecurityLevel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataEntity))]
        System.Threading.Tasks.Task DeleteSecurityLevelAsync(string Token);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class ServiceCapabilities
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private uint maxLimitField;
        
        private uint maxAuthenticationProfilesField;
        
        private uint maxPoliciesPerAuthenticationProfileField;
        
        private uint maxSecurityLevelsField;
        
        private uint maxRecognitionGroupsPerSecurityLevelField;
        
        private uint maxRecognitionMethodsPerRecognitionGroupField;
        
        private bool clientSuppliedTokenSupportedField;
        
        private string[] supportedAuthenticationModesField;
        
        public ServiceCapabilities()
        {
            this.clientSuppliedTokenSupportedField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxLimit
        {
            get
            {
                return this.maxLimitField;
            }
            set
            {
                this.maxLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxAuthenticationProfiles
        {
            get
            {
                return this.maxAuthenticationProfilesField;
            }
            set
            {
                this.maxAuthenticationProfilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxPoliciesPerAuthenticationProfile
        {
            get
            {
                return this.maxPoliciesPerAuthenticationProfileField;
            }
            set
            {
                this.maxPoliciesPerAuthenticationProfileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxSecurityLevels
        {
            get
            {
                return this.maxSecurityLevelsField;
            }
            set
            {
                this.maxSecurityLevelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxRecognitionGroupsPerSecurityLevel
        {
            get
            {
                return this.maxRecognitionGroupsPerSecurityLevelField;
            }
            set
            {
                this.maxRecognitionGroupsPerSecurityLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint MaxRecognitionMethodsPerRecognitionGroup
        {
            get
            {
                return this.maxRecognitionMethodsPerRecognitionGroupField;
            }
            set
            {
                this.maxRecognitionMethodsPerRecognitionGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ClientSuppliedTokenSupported
        {
            get
            {
                return this.clientSuppliedTokenSupportedField;
            }
            set
            {
                this.clientSuppliedTokenSupportedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] SupportedAuthenticationModes
        {
            get
            {
                return this.supportedAuthenticationModesField;
            }
            set
            {
                this.supportedAuthenticationModesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class SecurityLevelExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class RecognitionGroupExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class RecognitionMethodExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class RecognitionMethod
    {
        
        private string recognitionTypeField;
        
        private int orderField;
        
        private RecognitionMethodExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecognitionType
        {
            get
            {
                return this.recognitionTypeField;
            }
            set
            {
                this.recognitionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Order
        {
            get
            {
                return this.orderField;
            }
            set
            {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RecognitionMethodExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class RecognitionGroup
    {
        
        private RecognitionMethod[] recognitionMethodField;
        
        private RecognitionGroupExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecognitionMethod", Order=0)]
        public RecognitionMethod[] RecognitionMethod
        {
            get
            {
                return this.recognitionMethodField;
            }
            set
            {
                this.recognitionMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RecognitionGroupExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class AuthenticationProfileExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class AuthenticationPolicyExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class SecurityLevelConstraintExtension
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class SecurityLevelConstraint
    {
        
        private bool activeRegularScheduleField;
        
        private bool activeSpecialDayScheduleField;
        
        private string authenticationModeField;
        
        private string securityLevelTokenField;
        
        private SecurityLevelConstraintExtension extensionField;
        
        public SecurityLevelConstraint()
        {
            this.authenticationModeField = "pt:SingleCredential";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ActiveRegularSchedule
        {
            get
            {
                return this.activeRegularScheduleField;
            }
            set
            {
                this.activeRegularScheduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool ActiveSpecialDaySchedule
        {
            get
            {
                return this.activeSpecialDayScheduleField;
            }
            set
            {
                this.activeSpecialDayScheduleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("pt:SingleCredential")]
        public string AuthenticationMode
        {
            get
            {
                return this.authenticationModeField;
            }
            set
            {
                this.authenticationModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SecurityLevelToken
        {
            get
            {
                return this.securityLevelTokenField;
            }
            set
            {
                this.securityLevelTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public SecurityLevelConstraintExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class AuthenticationPolicy
    {
        
        private string scheduleTokenField;
        
        private SecurityLevelConstraint[] securityLevelConstraintField;
        
        private AuthenticationPolicyExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ScheduleToken
        {
            get
            {
                return this.scheduleTokenField;
            }
            set
            {
                this.scheduleTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SecurityLevelConstraint", Order=1)]
        public SecurityLevelConstraint[] SecurityLevelConstraint
        {
            get
            {
                return this.securityLevelConstraintField;
            }
            set
            {
                this.securityLevelConstraintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AuthenticationPolicyExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityLevelInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityLevel))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationProfileInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationProfile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/pacs")]
    public partial class DataEntity
    {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string token
        {
            get
            {
                return this.tokenField;
            }
            set
            {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SecurityLevel))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class SecurityLevelInfo : DataEntity
    {
        
        private string nameField;
        
        private int priorityField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class SecurityLevel : SecurityLevelInfo
    {
        
        private RecognitionGroup[] recognitionGroupField;
        
        private SecurityLevelExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RecognitionGroup", Order=0)]
        public RecognitionGroup[] RecognitionGroup
        {
            get
            {
                return this.recognitionGroupField;
            }
            set
            {
                this.recognitionGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SecurityLevelExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticationProfile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class AuthenticationProfileInfo : DataEntity
    {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl")]
    public partial class AuthenticationProfile : AuthenticationProfileInfo
    {
        
        private string defaultSecurityLevelTokenField;
        
        private AuthenticationPolicy[] authenticationPolicyField;
        
        private AuthenticationProfileExtension extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DefaultSecurityLevelToken
        {
            get
            {
                return this.defaultSecurityLevelTokenField;
            }
            set
            {
                this.defaultSecurityLevelTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationPolicy", Order=1)]
        public AuthenticationPolicy[] AuthenticationPolicy
        {
            get
            {
                return this.authenticationPolicyField;
            }
            set
            {
                this.authenticationPolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AuthenticationProfileExtension Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationProfileInfo", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetAuthenticationProfileInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetAuthenticationProfileInfoRequest()
        {
        }
        
        public GetAuthenticationProfileInfoRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationProfileInfoResponse", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetAuthenticationProfileInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationProfileInfo")]
        public Quick.Onvif.AuthenticationBehavior.AuthenticationProfileInfo[] AuthenticationProfileInfo;
        
        public GetAuthenticationProfileInfoResponse()
        {
        }
        
        public GetAuthenticationProfileInfoResponse(Quick.Onvif.AuthenticationBehavior.AuthenticationProfileInfo[] AuthenticationProfileInfo)
        {
            this.AuthenticationProfileInfo = AuthenticationProfileInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationProfileInfoList", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetAuthenticationProfileInfoListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=1)]
        public string StartReference;
        
        public GetAuthenticationProfileInfoListRequest()
        {
        }
        
        public GetAuthenticationProfileInfoListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationProfileInfoListResponse", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetAuthenticationProfileInfoListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        public string NextStartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationProfileInfo")]
        public Quick.Onvif.AuthenticationBehavior.AuthenticationProfileInfo[] AuthenticationProfileInfo;
        
        public GetAuthenticationProfileInfoListResponse()
        {
        }
        
        public GetAuthenticationProfileInfoListResponse(string NextStartReference, Quick.Onvif.AuthenticationBehavior.AuthenticationProfileInfo[] AuthenticationProfileInfo)
        {
            this.NextStartReference = NextStartReference;
            this.AuthenticationProfileInfo = AuthenticationProfileInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationProfiles", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetAuthenticationProfilesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetAuthenticationProfilesRequest()
        {
        }
        
        public GetAuthenticationProfilesRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationProfilesResponse", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetAuthenticationProfilesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationProfile")]
        public Quick.Onvif.AuthenticationBehavior.AuthenticationProfile[] AuthenticationProfile;
        
        public GetAuthenticationProfilesResponse()
        {
        }
        
        public GetAuthenticationProfilesResponse(Quick.Onvif.AuthenticationBehavior.AuthenticationProfile[] AuthenticationProfile)
        {
            this.AuthenticationProfile = AuthenticationProfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationProfileList", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetAuthenticationProfileListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=1)]
        public string StartReference;
        
        public GetAuthenticationProfileListRequest()
        {
        }
        
        public GetAuthenticationProfileListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAuthenticationProfileListResponse", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetAuthenticationProfileListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        public string NextStartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("AuthenticationProfile")]
        public Quick.Onvif.AuthenticationBehavior.AuthenticationProfile[] AuthenticationProfile;
        
        public GetAuthenticationProfileListResponse()
        {
        }
        
        public GetAuthenticationProfileListResponse(string NextStartReference, Quick.Onvif.AuthenticationBehavior.AuthenticationProfile[] AuthenticationProfile)
        {
            this.NextStartReference = NextStartReference;
            this.AuthenticationProfile = AuthenticationProfile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityLevelInfo", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetSecurityLevelInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetSecurityLevelInfoRequest()
        {
        }
        
        public GetSecurityLevelInfoRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityLevelInfoResponse", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetSecurityLevelInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SecurityLevelInfo")]
        public Quick.Onvif.AuthenticationBehavior.SecurityLevelInfo[] SecurityLevelInfo;
        
        public GetSecurityLevelInfoResponse()
        {
        }
        
        public GetSecurityLevelInfoResponse(Quick.Onvif.AuthenticationBehavior.SecurityLevelInfo[] SecurityLevelInfo)
        {
            this.SecurityLevelInfo = SecurityLevelInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityLevelInfoList", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetSecurityLevelInfoListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=1)]
        public string StartReference;
        
        public GetSecurityLevelInfoListRequest()
        {
        }
        
        public GetSecurityLevelInfoListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityLevelInfoListResponse", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetSecurityLevelInfoListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        public string NextStartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("SecurityLevelInfo")]
        public Quick.Onvif.AuthenticationBehavior.SecurityLevelInfo[] SecurityLevelInfo;
        
        public GetSecurityLevelInfoListResponse()
        {
        }
        
        public GetSecurityLevelInfoListResponse(string NextStartReference, Quick.Onvif.AuthenticationBehavior.SecurityLevelInfo[] SecurityLevelInfo)
        {
            this.NextStartReference = NextStartReference;
            this.SecurityLevelInfo = SecurityLevelInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityLevels", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetSecurityLevelsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Token")]
        public string[] Token;
        
        public GetSecurityLevelsRequest()
        {
        }
        
        public GetSecurityLevelsRequest(string[] Token)
        {
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityLevelsResponse", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetSecurityLevelsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SecurityLevel")]
        public Quick.Onvif.AuthenticationBehavior.SecurityLevel[] SecurityLevel;
        
        public GetSecurityLevelsResponse()
        {
        }
        
        public GetSecurityLevelsResponse(Quick.Onvif.AuthenticationBehavior.SecurityLevel[] SecurityLevel)
        {
            this.SecurityLevel = SecurityLevel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityLevelList", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetSecurityLevelListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        public int Limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=1)]
        public string StartReference;
        
        public GetSecurityLevelListRequest()
        {
        }
        
        public GetSecurityLevelListRequest(int Limit, string StartReference)
        {
            this.Limit = Limit;
            this.StartReference = StartReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSecurityLevelListResponse", WrapperNamespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", IsWrapped=true)]
    public partial class GetSecurityLevelListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=0)]
        public string NextStartReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.onvif.org/ver10/authenticationbehavior/wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("SecurityLevel")]
        public Quick.Onvif.AuthenticationBehavior.SecurityLevel[] SecurityLevel;
        
        public GetSecurityLevelListResponse()
        {
        }
        
        public GetSecurityLevelListResponse(string NextStartReference, Quick.Onvif.AuthenticationBehavior.SecurityLevel[] SecurityLevel)
        {
            this.NextStartReference = NextStartReference;
            this.SecurityLevel = SecurityLevel;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface AuthenticationBehaviorPortChannel : Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class AuthenticationBehaviorPortClient : System.ServiceModel.ClientBase<Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort>, Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort
    {
        
        public AuthenticationBehaviorPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.ServiceCapabilities> GetServiceCapabilitiesAsync()
        {
            return base.Channel.GetServiceCapabilitiesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoResponse> Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort.GetAuthenticationProfileInfoAsync(Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoRequest request)
        {
            return base.Channel.GetAuthenticationProfileInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoResponse> GetAuthenticationProfileInfoAsync(string[] Token)
        {
            Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoRequest inValue = new Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoRequest();
            inValue.Token = Token;
            return ((Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort)(this)).GetAuthenticationProfileInfoAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoListResponse> GetAuthenticationProfileInfoListAsync(Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileInfoListRequest request)
        {
            return base.Channel.GetAuthenticationProfileInfoListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfilesResponse> Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort.GetAuthenticationProfilesAsync(Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfilesRequest request)
        {
            return base.Channel.GetAuthenticationProfilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfilesResponse> GetAuthenticationProfilesAsync(string[] Token)
        {
            Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfilesRequest inValue = new Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfilesRequest();
            inValue.Token = Token;
            return ((Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort)(this)).GetAuthenticationProfilesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileListResponse> GetAuthenticationProfileListAsync(Quick.Onvif.AuthenticationBehavior.GetAuthenticationProfileListRequest request)
        {
            return base.Channel.GetAuthenticationProfileListAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> CreateAuthenticationProfileAsync(Quick.Onvif.AuthenticationBehavior.AuthenticationProfile AuthenticationProfile)
        {
            return base.Channel.CreateAuthenticationProfileAsync(AuthenticationProfile);
        }
        
        public System.Threading.Tasks.Task SetAuthenticationProfileAsync(Quick.Onvif.AuthenticationBehavior.AuthenticationProfile AuthenticationProfile)
        {
            return base.Channel.SetAuthenticationProfileAsync(AuthenticationProfile);
        }
        
        public System.Threading.Tasks.Task ModifyAuthenticationProfileAsync(Quick.Onvif.AuthenticationBehavior.AuthenticationProfile AuthenticationProfile)
        {
            return base.Channel.ModifyAuthenticationProfileAsync(AuthenticationProfile);
        }
        
        public System.Threading.Tasks.Task DeleteAuthenticationProfileAsync(string Token)
        {
            return base.Channel.DeleteAuthenticationProfileAsync(Token);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoResponse> Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort.GetSecurityLevelInfoAsync(Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoRequest request)
        {
            return base.Channel.GetSecurityLevelInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoResponse> GetSecurityLevelInfoAsync(string[] Token)
        {
            Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoRequest inValue = new Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoRequest();
            inValue.Token = Token;
            return ((Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort)(this)).GetSecurityLevelInfoAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoListResponse> GetSecurityLevelInfoListAsync(Quick.Onvif.AuthenticationBehavior.GetSecurityLevelInfoListRequest request)
        {
            return base.Channel.GetSecurityLevelInfoListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelsResponse> Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort.GetSecurityLevelsAsync(Quick.Onvif.AuthenticationBehavior.GetSecurityLevelsRequest request)
        {
            return base.Channel.GetSecurityLevelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelsResponse> GetSecurityLevelsAsync(string[] Token)
        {
            Quick.Onvif.AuthenticationBehavior.GetSecurityLevelsRequest inValue = new Quick.Onvif.AuthenticationBehavior.GetSecurityLevelsRequest();
            inValue.Token = Token;
            return ((Quick.Onvif.AuthenticationBehavior.AuthenticationBehaviorPort)(this)).GetSecurityLevelsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Quick.Onvif.AuthenticationBehavior.GetSecurityLevelListResponse> GetSecurityLevelListAsync(Quick.Onvif.AuthenticationBehavior.GetSecurityLevelListRequest request)
        {
            return base.Channel.GetSecurityLevelListAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> CreateSecurityLevelAsync(Quick.Onvif.AuthenticationBehavior.SecurityLevel SecurityLevel)
        {
            return base.Channel.CreateSecurityLevelAsync(SecurityLevel);
        }
        
        public System.Threading.Tasks.Task SetSecurityLevelAsync(Quick.Onvif.AuthenticationBehavior.SecurityLevel SecurityLevel)
        {
            return base.Channel.SetSecurityLevelAsync(SecurityLevel);
        }
        
        public System.Threading.Tasks.Task ModifySecurityLevelAsync(Quick.Onvif.AuthenticationBehavior.SecurityLevel SecurityLevel)
        {
            return base.Channel.ModifySecurityLevelAsync(SecurityLevel);
        }
        
        public System.Threading.Tasks.Task DeleteSecurityLevelAsync(string Token)
        {
            return base.Channel.DeleteSecurityLevelAsync(Token);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
